name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test (std)
      run: cargo test --verbose --all # std
    - name: Test (no-std)
      run: cargo test --verbose --all --no-default-features # no-std
